### ISSUE TITLE
Moved email to inbox not tracked in CRM

### ISSUE THREAD

**Issue by PeterJWouda** [dseph/EwsEditor#16]
When we move email form a spam folder to the inbox it does not get tracked in CRM but it does not appear in the Show To-Be 
Tracked Items 
Is there a way to get all thes items tracked afterwards?
"[Name:] crmLinkState [PropSet:] PublicStrings Microsoft.Exchange.WebServices.Data.MapiPropertyType.Double value 2" is missing with these email items

**Comment by dseph** [comment]
Hello Peter. I have little familiarity with CRM.  That property appears to be a custom X-header which CRM may be using.  A support case should be opened with the CRM team since they would be familiar with how it tracks changes (likely they are using notification).  It could be that it tracks messages arriving in the inbox and not email being moved into the folder - ie those are two different events and CRM would need to subscribe for both to get notified for both events.
